
services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: larrytao
      POSTGRES_PASSWORD: griddy
      POSTGRES_DB: griddy-city
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/apps/backend/db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://larrytao:griddy@database:5432/griddy-city
      - REDIS_URL=redis://redis:6379
    env_file:
    - ./backend/apps/backend/.env
    depends_on:
      - database
      - redis

volumes:
  postgres_data: 
  redis_data: