version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=larrytao
      - POSTGRES_PASSWORD=griddy
      - POSTGRES_DB=griddy-city
      - DATABASE_URL=postgres://larrytao:griddy@db:5432/griddy-city
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=larrytao
      - POSTGRES_PASSWORD=griddy
      - POSTGRES_DB=griddy-city
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 